name: 'git-ftp-action'
description: 'Uses git-ftp and GitHub actions to deploy a GitHub repository to a FTP server.'
inputs:
  url:
    description: 'URL'
    required: true
  user:
    description: 'FTP login name'
    required: true
  password:
    description: 'FTP password'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'